version: '2'

services:
  myapp:
    image: 'bitnami/symfony:1'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
    environment:
      - SYMFONY_PROJECT_NAME=calimed_todo
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=calimed
      - MARIADB_PASSWORD=sosecuredpassword
      - MARIADB_DATABASE=calimed_todo
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=calimed
      - MARIADB_PASSWORD=sosecuredpassword
      - MARIADB_DATABASE=calimed_todo
